### ISSUE TITLE
Error plotting single setup animated mode shapes 

### ISSUE THREAD

**Issue by Ayubirad** [dagghe/pyOMA2#23]
**Describe the bug**
Hi there. I hope you're having a good week. It's just that when I ran the second example, Example2.ipynb, it was not able to plot the animated mode shapes as was expected.

**To Reproduce**
Just run the Example2.ipynb

**Expected behavior**
In previous versions this was not an issue and mode shapes were plotted accordingly.

**Desktop (please complete the following information):**
 - pyoma2 version: latest
 - OS: Windows 11
 - Version 24H2

**Additional context or possible solutions**
This is the message I received:
Pali_ss.anim_mode_geo2(algo_res=ssicov.result, mode_nr=1, scaleF=3)
Traceback (most recent call last):

Cell In[4], line 1
_ = Pali_ss.anim_mode_geo2(algo_res=ssicov.result, mode_nr=1, scaleF=3)

AttributeError: 'SingleSetup' object has no attribute 'anim_mode_geo2'

also when plotting the mode shapes the following warning persist:

pyoma2\functions\gen.py
FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_phi_map = sens_map.replace(mapping).astype(float)

**Comment by dfm88** [comment]
Hi @Ayubirad, so the rename of method from `anim_mode_g2` to `anim_mode_geo2` is still to be released (see the changelog [CHANGELOG.md](https://github.com/dagghe/pyOMA2/blob/main/CHANGELOG.md))
I guess somehow you are using the Example script from the main branch and not from the last [v1.0.0](https://github.com/dagghe/pyOMA2/tree/v1.0.0) release tag.

**Comment by Ayubirad** [comment]
Exactly! I used `pip install pyOMA-2`, please would you tell me what command should be used to install v1.0.0 of the package?

**Comment by dfm88** [comment]
Yes it is correct, you installed last released version that is v1.0.0 so here you find the corresponding code of that version (Examples are not included in the downloaded package, so copy them from the source code of the relative tag linked here [v1.0.0](https://github.com/dagghe/pyOMA2/tree/v1.0.0)
