### ISSUE TITLE
Issue loading the pyOMA-2 package unsing the traditional pip install

### ISSUE THREAD

**Issue by MArnaud** [dagghe/pyOMA2#4]
Dear authors, I'm following with great interest the developments you're making with this new version of pyOMA2. However, I can't install the package using the traditional pip install command. I get the following message: 
"Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pyOMA-2 (from versions: none)
ERROR: No matching distribution found for pyOMA-2"
Can you confirm that the package is available?
Thank you very much.
MArnaud

**Comment by dfm88** [comment]
> Dear authors, I'm following with great interest the developments you're making with this new version of pyOMA2. However, I can't install the package using the traditional pip install command. I get the following message: "Defaulting to user installation because normal site-packages is not writeable ERROR: Could not find a version that satisfies the requirement pyOMA-2 (from versions: none) ERROR: No matching distribution found for pyOMA-2" Can you confirm that the package is available? Thank you very much. MArnaud

This error is probably related to the python version, the package currently supports `3.8 <= python <= 3.11` as per https://pypi.org/project/pyOMA-2/.
Please try to check your python version and let us know.

**Comment by dagghe** [comment]
Dear user, could you please provide more info so that we can reproduce the error? On windows I’ve tried pip installing the module on an empty conda environment and got no error…

**Comment by MArnaud** [comment]
Dear @dagghe. Sorry for the delay. I can confirm that it was indeed a version problem. I'm using ubuntu 18.04.6. I had to update to version 3.9.16 of python. I'll continue testing and keep you posted. Thanks a lot!
