### ISSUE TITLE
MPC and MPD conditions

### ISSUE THREAD

**Issue by Ayubirad** [dagghe/pyOMA2#6]
Dear @dagghe, 

Thanks for your brilliant package, is it possible to add the following mask condition to the SSI poles as well?
MPC<0.7 and MPD>0.3: Typically a mode shape with these values is considered as spurious.

If you could add the plot of 1st singular value as the second Y-axis on the SSI stabilization plot, and the values of MPC, MPD, and MCF on the final selected mode shapes, that'd be wonderful.

Best regards,
Ayubirad

**Comment by dagghe** [comment]
Dear @Ayubirad thanks for the feedback. The functions you mention are already implemented (see the Gen_funct.py module). However I see your point and we will consider to add this additional criterion in the near future. When it comes to the singular value plot on a twin axis, this is already on the to do list and will probably added in the next update.

**Comment by Ayubirad** [comment]
Dear @dagghe 

Thank you very much for taking the time to consider my request. I am reaching out to kindly ask if you could review this modification in the `Gen_funct.py` file to ensure that it correctly follows the MPC-MPD criterion. I would greatly appreciate your expertise to confirm if everything is in order or if I have overlooked something.

```
if cond1 < err_fn and cond2 < err_xi and cond3 < err_ms:
                        mpc = MPC(phi_n[i, :])
                        mpd = MPD(phi_n[i, :])
                        if mpc >= 0.7 and mpd <= 0.3:
                            Lab[i, ii] = 7  # Condition for stable mode
```

**Comment by dagghe** [comment]
feature added in v0.5.1
